var slider = document.getElementById("slider");
var number = document.getElementById("number");

  slider.oninput = function() {
   number.innerHTML = slider.value;

   var value = parseInt(slider.value) + 6;
   var months = ["Januari ", "Februari ", "Maart ", "April ", "Mei ", "Juni ", "Juli ", "Augustus ", "September ", "Oktober ", "November ", "December "]
   var years = ["1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945"]
   var info = [
    "Marco Polo brug incident. / Start inval China door Japan.",
    "Japan bezet Beijing, Slag om Shanghai begint.",
    "Communistische troepen winnen veldslag tegen Japan",
    "Nazi Duitsland belooft Belgie niet binnen te vallen. / Japanse troepen marcheren naar Nanking (toenmalige hoofdstad van China).",
    "Japan verovert Shanghai. / Italie betreedt anti-comintern pact .",
    "Slag om Nanking start en eindigd, Japan vermoordt meer dan 300000 Chinezen. / Italie trekt zich terug uit de league of nations.",
    "Niets van belang.",
    "Oostenrijk stemt (onder bedreiging) toe aan meer Nazi invloed in haar regering. / Carol II van Roemenie neemt dictatoriale macht.",
    "De anschluss van Oostenrijk en Duitsland. / Mussolini vergroot macht over Italiaans leger.",
    "Engeland ondertekent verdrag met Italie waarmee controle over Ethiopie wordt erkend.",
    "Tsjecho-Slowakije start mobilisatie van leger aan Duitse grens na militaire activiteit van de Duitsers. / Duitsland declareert haar intentie om Tsjecho-Slowakije met militaire macht binnen te vallen.",
    "Overstroming van de gele rivier in China door haar overheid om opmars van Japan tegen te gaan.",
    "Groot-Brittanie weigert bijeenkomst met Frankrijk, Duitsland en de Sovjet-unie omdat zij de Sovjet-unie niet wil erkennen.",
    "Hitler spreekt met Hongaarse regent Horthy over inval Tsjecho-Slowakije.",
    "Sudeten crisis wat leidt tot de Munich overeenkomst, hieruit volgt de 'peace for our time' aankondiging van Chamberlain.",
    "Duitsland treedt het Sudetenland binnen.",
    "Kristallnacht in Duitsland, tientallen Joodse winkels worden gevandalizeerd door de Nazi's.",
    "Adolf Hitler wordt time magazijn's 'Man of the Year'. / Nucleare fissie wordt ontdekt.",
    "Amelia Earhart wordt dood verklaard. / Hitler geeft een speech waarin hij waarschuwt voor de 'oorlog van de Joodse bankiers'.",
    "Regering van Fransisco Franco (dictator van Spanje) wordt erkend door Frankrijk en Engeland.",
    "Duitsland bezet het overige gebied van Tsjechie en zet een Marionettenstaat op in Slowakije. / 1939 Liechtenstein Putsch vindt plaats.",
    "Spaanse burgeroorlog komt ten einde. /  Duitsland begint met plannen voor inval van Polen. / Italiaanse inval van Albanie.",
    "Batman verschijnt voor het eerst in stripboeken. / Duitsland en Italie onderteken het 'verdrag van staal'.",
    "Laatste publieke executie door middel van guillotine in Frankrijk.",
    "De laatste overige Joodse bedrijven worden door de Nazi's gesloten.",
    "Duitlsand ondertekent het Molotov-Ribbentrop pact samen met de Sovjet-Unie. / Polen begint militaire mobilisatie tegen Duitsland. ",
    "Duitsland en de Sovjet-Unie vallen Polen binnen, start Europese en Afrikaanse front van de Tweede wereldoorlog.",
    "Officiele annexatie van west-Polen door Duitsland.",
    "De Sovjet-Unie valt Finland binnen, Start van de Winteroorlog.",
    "De Sovjet-Unie zet een marionette staat op in hun bezette gebied van Finland.",
    "Groot-Brittanie begint met rantsoenering.",
    "Datum voor 1940 Winter Olympische spelen in Duitsland gezet. ",
    "Finland en de Sovjet-Unie ondertekenen een vredesverdrag.",
    "Duitsland voert operatie Weserubung, de inval van Noorwegen en Denemarken, uit. ",
    "Duitsland valt de BeNeLux binnen om naar Frankrijk te komen. / Winston Churchill wordt, na het aftreden van Chamberlain, de nieuwe minister president van Groot Brittanie. / Rotterdam wordt plat gebombardeerd waardoor Nederland staakt met vechten.",
    "Einde evacuatie van 300.000 soldaten bij Duinkerken. / Frankrijk geeft zichzelf over aan de Nazi's.",
    "Battle of Britain. /  Duitsland geeft een offerte voor vrede aan Engeland die direct geweigerd wordt.",
    "Italie en Duitsland dwingen Roemenie om noord-Transylvanie af te staan aan Hongarije.",
    "De koning van Roemenie Treedt af. / Japan valt Frans-Indochina binnen. / Japan, Duitsland en Italie ondertekenen het tripartite verdrag.",
    "Einde battle of Britain. / Italie valt Griekenland binnen.",
    "Het Griekse leger wint een slag, met een minderheid tegen, Italie. / Roemenie en Slowakije treden de Axis machten binnen.",
    "Amerika kondigt een plan aan om hulp naar Engeland te sturen.",
    "Franklin D. Roosevelt wordt ingezworen voor een derde termijn.",
    "Duitse generaal, Erwin Rommel komt aan in Tripoli. / Nederlanders startten de eerste opstand tegen de Duitsers.",
    "Bulgarije treedt de Axis toe. / De Lend-Lease akte wordt in Amerikaanse wet doorgevoerd. / Yoegoslavie treedt de Axis binnen, staatsgreep im Joegoslavie.",
    "Duitsland valt Joegoslavie binnen. / Duitsland assisteert met de inval van Griekenland en bezet Athene.",
    "Engeland start met militaire activiteit tegen Iraq. / Addis Ababa is teruggenomen van de Italianen.",
    "Duitsland valt de Sovjet-Unie binnen, de rest van de axis gaat met Duitsland mee. /  Finland start, met steun van Duitsland, de vervolgingsoorlog tegen de Sovjet-Unie.",
    "Hitler beveelt om plannen voor de Holocaust gemaakt te laten worden.",
    "Gemeenschappelijke invasie van Iran door Engeland en de Sovjet-Unie.",
    "Eerste invoering van gaskamers in Duitse concentratiekampen.",
    "Duitsland start een all-out offensief richting Moscow.",
    "Het Duitse offensief wordt tegengehouden door de winter.",
    "Pearl Harbor, de aanval van Japan op een Amerikaanse zeebasis. / De Sovjet-Unie start haar weer-offensief tegen Duitsland. / Duitsland en Italie verklaren Amerika de oorlog.",
    "Japan valt Nederlands Oost-Indie binnen. / De eerste Amerikaanse soldaten landen in Europa.",
    "Japanse bezetting van Singapore.",
    "Amerika start met het stoppen van Jappaners in kampen. / Slag bij Midway, grote overwinning voor de Amerikaanse zeemacht.",
    "Een Franse generaal ontsnapt uit gevangenschap, hij komt naar beneden via een touw aan de rand van een cliff. Hij weet over de Zwitserse grens te ontsnappen.",
    "Mexico verklaart Duitsland de oorlog.",
    "Belegering van Tobruk, geleid door Erwin Rommel.",
    "De familie van Anne Frank moet verbergen in het achterhuis.",
    "Gandhi wordt gearresteerd. / Slag bij Stalingrad. / Brazilie verklaart Duitsland de oorlog.",
    "Japan leidt haar eerste verlies op land.",
    "Duitsland geeft de opdracht alle geallierde officieren die gevangen genomen worden te executeren.",
    "Een wederaanval van Georgy Zhukov keert het tij bij de slag om Stalingrad. / De Franse zeemacht zinkt haar schepen om ze uit Nazi handen te houden.",
    "De eerste zelfvoorzienende nucleare ketenreactie is uitgevoerd in Chicago. / Het eerste woord over de holocaust dringt naar buiten.",
    "De opstand van Warschau begint.",
    "Einde slag om Stalingrad, de aanvallende legers geven over.",
    "De eerste totaal electronische computer wordt ingezet tegen de Duitsers.",
    "De ghetto van Warschau komt in opstand nadat de Nazi's probeerden de laatste joden daar dood te maken.",
    "Duitse en Italiaanse troepen in noord-Afrika geven zich over aan de geallieerden.",
    "Een nieuw offensief van de geallierden tegen Japan begint.",
    "Benito Mussolini wordt gearresteerd door de grote raad van fascisme.",
    "De koning van Bulgarije sterft onder verdachte omstandigheden, zijn 6 jaar oude zoon neemt de troon over.",
    "Italie wordt binnegvallen door de geallierden.",
    "Een nieuwe overheid in Italie sluit zich aan bij de geallierden en verklaart Duitsland de oorlog.",
    "Kiev wordt door Sovjet troepen bevrijd van de Duitsers.",
    "Eisenhower wordt 'Supreme Allied Commander Europe'.",
    "De Sovjet-Unie start een tegenaanval bij Leningrad en Novgorod uiteindelijk wordt hierdoor de belegering van Leningrad na 2 jaar gestopt.",
    "Amerikaanse troepen bezetten de Marshall-eilanden.",
    "Duitse troepen bezetten Hongarije.",
    "Geallierde bombardementen op diverse grote steden in zuid-oost Europa.",
    "Duitse troepen worden door de Sovjets uit Sevastopol gedrongen.",
    "Rome wordt bezet door de geallierden, de eerste hoofdstad van een axis-macht die valt. /  D-Dat, de inval van de geallierde troepen in Normandie.",
    "Hitler overleeft een poging tot moord, de betrokkenen worden de volgende dag geexecuteerd.",
    "De Warschau-Opstand begint. / De familie van Anne-Frank is verraden en opgepakt. / Een opstand in Parijs begint om de stad vrij te maken van de Duitsers.",
    "De hongerwinter in het nog bezette gebied van Nederland. / De geallierden bevrijden Brussel.",
    "Nazi-troepn weten de Warschau opstand te kwellen. / De eerste Duitse stad, Aachen, wordt door Amerikaanse troepen bezet.",
    "Franklin D. Roosevelt wint de Amerikaanse verkiezingen voor een vierde termijn.",
    "Begin van strijd tussen Communisten en Monarchisten in Griekenland waar uiteindelijk een burgeroorlog door uitrbeekt.",
    "Adolf Hitler begint met wonen in de Fuhrerbunker in Berlijn. / De Sovjet-Unie bezet Warschau.",
    "Manila, de hoofdstad van de Filipijnen, wordt bevrijdt door Amerikaanse en Filipijnse troepen. / Yalta conferentie, hier besluiten de geallierden hoe Europa er na de oorlog uit zal zien.",
    "Josip Broz Tito vormt een tijdelijke overheid in Joegoslavie.",
    "Slag bij Okinawa, Amerikaanse troepen landen op Okinawa. / De slag om Berlijn begint. / Het lijk van Mussolini wordt opgehangen bij een tankstation. / Adolf hitler pleegt zelfmoord.",
    "De Sovjet-Unie kondigt de val van Berlijn aan. / Nazi Duitsland geeft zich over aan de geallierden.",
    "De koning van Noorwegen keert terug na precies vijf jaar sinds het begin van zijn banningschap. / Einde van de slag bij Okinawa, de Amerikanen verslaan de Japaners.",
    "Duitsland wordt verdeelt onder de geallierde bezettende troepen. / Truman geeft toestemming voor het gebruik van de atoombommen op Japan.",
    "Amerika laat twee atoombommen vallen op Japan. / De Japanse kijzer kondigt aan dat Japan zich overgeeft.",
    "Einde van de 2e wereldoorlog na de overgave van de laatste Japanse soldaten."
    ]
    
   document.getElementById("datum").innerHTML = (months[(value % 12)] + years[Math.floor(value / 12)]);
   document.getElementById("info").innerHTML = (info[parseInt(value) - 6])
}